@startgantt
language ru

project starts the 2025-04-01

'Stage1

[Документация] requires 7 days
[Проектирование и создание БД] requires 1 days
[Разработка проекта] requires 21 days
[Финальное тестирование] requires 1 days
[Зачёт] requires 1 days

'Stage2

[Постановка идеи] requires 4 days
[Определение плана разработки] requires 1 days

'Stage1Diagram

[Документация] starts at 2025-04-01
[Проектирование и создание БД] starts at 2025-04-07
[Разработка проекта] starts at [Документация]'s end
[Финальное тестирование] starts at [Разработка проекта]'s end
[Зачёт] starts at [Финальное тестирование]'s end

[Зачёт] is colored in pink

' Saturday are colored in LightPink
' Sunday are colored in LightPink

'Stage2Diagram

[Постановка идеи] starts at 2025-05-01
[Определение плана разработки] starts  at 2025-05-04

@endgantt